name: mcsce
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.7,<3.10
    - numpy=1
    - numba>=0.53.0
    - scipy=1
    - pip
    - tox=3
    - tensorflow=1.14
    - keras=2.3
    - tqdm
    - pathos
